### PR TITLE
Update classes/breadcrumbs.php

### PR DESCRIPTION
**Pull request by sturple**
Hi, @rhukster  
Added feature to add URI params to breadcrumbs.
Updated build function
Added $grav variable, and added  if statement and foreach statement to check for uri params.

### CODE REVIEW

**Comment by flaviocopes** [comment]
@sturple can you describe what is the URI params usage?

**Comment by sturple** [comment]
It gets the categories or tags, or whatever from the uri.param('') to add it to breadcrumbs.
For example if your url had http://myurl.com/blog/category:News%20Release
Then the Breadcrumb would read Home > Blog > News Release

**Comment by rhukster** [comment]
I'm not sure this is really expected behavior.  Your filtering based on category, but your not actually on a `News Release` page. The breadcrumbs generally show your position in the hierarchy of your site, but this page does not actually exist.

**Comment by sturple** [comment]
@rhukster @flaviocopes 
Breadcrumbs can be used to display more then actual pages 
For example have a look at the following articles 
* https://www.smashingmagazine.com/2009/03/breadcrumbs-in-web-design-examples-and-best-practices/
* https://en.wikipedia.org/wiki/Breadcrumb_(navigation)
* http://marketingland.com/breadcrumb-links-good-user-experience-yes-97848

These articles talk about page navigation as well as attribute navigation.

This is how i would code a website using breadcrumbs in this manner, for example it is an easy click to the Blog breadcrumb to remove the News Release Category. in the following breadcrumb.

Home > Blog > News Release

This could have a configuration in the settings to enable uri.params Breadcrumbs.
Of course you need to make the final decision on what to do, I am just making recommendations on my experience.
Thanks for your considerations on my update, and thanks for a great cms.

Regards, 
Shawn

**Pull request closed without merging**
